language: scala
scala:
- 2.11.12
- 2.12.4
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
script:
  - sbt "++${TRAVIS_SCALA_VERSION}" validateJVM validateJS
sudo: false
